development:
  adapter: mysql2
  database: content_master_dev
  username: root
  password: "#1Varun0104"
  host: localhost
  encoding: utf8

test:
  database: content_master_test
  adapter: mysql2
  encoding: utf8
  username: root
  password: "#1Varun0104"
  host: localhost

production:
  adapter: mysql2
  database: content_master_production
  username: root
  password: "#1Varun0104"
  host: localhost
  encoding: utf8